# ワークフローの名前
name: Run pytest
# トリガーのイベント
on:
  push:
    branches: [ "main" ]

jobs:
  # ジョブのID
  pytest:
    # ジョブが実行されるマシンの種類
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      # （ワークフローがリポジトリにアクセスできるようにする）
      - name: Checkout
        # uses: 使用するアクション
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # pytestをインストール
      - name: Install dependencies
        # run: 実行するシェルコマンド
        # コマンドを複数行記述したい場合は「|」を使う
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest test --junit-xml results/pytest.xml
        # continue-on-error に true を指定することで、
        # 終了ステータスがエラーでもワークフローの実行が中断されなくなる
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python 3.7)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml